Repository stolostron/cert-policy-controller, pull requests merged in 2021-04, with the labels that each got.

#76 Update docs for open source
  .github/workflows/kind.yml
  CONTRIBUTING.md
  DCO
  Makefile
  README.md
Labels: approved, lgtm

#77 update to work with install instructions for ocm
  Makefile
  README.md
  deploy/clusterrole_binding.yaml
  deploy/operator.yaml
Labels: approved, lgtm

#78 add lease controller to report status as an addon
  .gitignore
  Makefile
  cmd/manager/main.go
  deploy/operator.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/common/namespace_selection.go
  pkg/common/namespace_selection_test.go
  pkg/controller/certificatepolicy/certificatepolicy_controller.go
  pkg/controller/certificatepolicy/certificatepolicy_controller_test.go
Labels: approved, lgtm

#79 fix lease name
  cmd/manager/main.go
Labels: approved, lgtm

#80 Update to trigger build for security vulnerability re-packaging
  README.md
Labels: approved, dco-signoff: yes, lgtm

#82 Update docs
  CONTRIBUTING.md
  DCO
  README.md
Labels: approved, dco-signoff: yes, lgtm

#83 Prevent GH Actions from running immediately
  .github/workflows/kind.yml
  SECURITY.md
Labels: approved, dco-signoff: yes, lgtm

#85 Remove RHACM references
  .github/workflows/kind.yml
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test
